### ISSUE TITLE
--docker-image doesn't work in 0.8.0

### ISSUE THREAD

**Issue by bhcopeland** [kernelci/tuxmake#91]
***In GitLab by @danrue on Nov 16, 2020, 17:56 GMT:***

The following command works with `--runtime docker`, and fails with `--runtime podman`. `--image` does work with both.

```
drue@jug:~/src/linux-mainline₿ tuxmake --docker-image 'docker.io/tuxmake/x86_64_gcc@sha256:f8218cbfad8ecf6628fc44db864a402070feb87ff43a880e1409649172d4bc8c' -r podman -k tinyconfig -e "KBUILD_BUILD_TIMESTAMP='Sun May  1 12:00:00 CEST 2011'" -e "KBUILD_BUILD_USER=tuxmake" -e "KBUILD_BUILD_HOST=tuxmake"
W: --docker-image is deprecated; use --image instead
Traceback (most recent call last):
  File "/home/drue/.local/bin/tuxmake", line 8, in <module>
    sys.exit(main())
  File "/home/drue/.local/lib/python3.8/site-packages/tuxmake/cli.py", line 98, in main
    result = build(**build_args, auto_cleanup=(not options.shell))
  File "/home/drue/.local/lib/python3.8/site-packages/tuxmake/build.py", line 506, in build
    builder = Build(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'docker_image'
```

**Assignees:** terceiro

*Migrated from GitLab: https://gitlab.com/Linaro/tuxmake/-/issues/91*

**Comment by bhcopeland** [comment]
***In GitLab by @danrue on Nov 16, 2020, 18:00 GMT:***

Actually I was using an old version of tuxmake with docker. Version 0.8.0 actually fails in the same way when using --docker-image with docker.

**Comment by bhcopeland** [comment]
***In GitLab by @terceiro on Nov 18, 2020, 12:34 GMT:***

mentioned in commit 83ff496c4bc2aaaae7d52b2765c133135a1a2206

**Comment by bhcopeland** [comment]
***In GitLab by @terceiro on Nov 18, 2020, 12:40 GMT:***

mentioned in commit 8efdf27f42b297ea8f6f910a4169f6d658728ce3
